### PR TITLE
Codetools 7902736

### PR DESCRIPTION
**Pull request by shurymury**
Add selected text to the dump, whether or not the test is empty. Add empty string for null return value.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Referenced JBS issue must only be used for a single change
- [x] Change must be properly reviewed

### Download
`$ git fetch https://git.openjdk.java.net/jemmy-v2 pull/2/head:pull/2`
`$ git checkout pull/2`

### CODE REVIEW

**Review by amresh-sahu — COMMENTED** [review]
Looks fine.

**Comment by akolarkunnu** [comment]
Just a thought - Is it a good idea to differentiate 'null' and empty string - May be by replacing "" with "null" when selectedText is null.
Also what about renaming 'selected' with 'selectedText' .

**Comment by shurymury** [comment]
> On Nov 10, 2020, at 10:58 PM, Muneer Kolarkunnu <notifications@github.com> wrote:
> 
> 
> Just a thought - Is it a good idea to differentiate 'null' and empty string - May be by replacing "" with "null" when selectedText is null.
> 

I thought about it. Null selection really means nothing is selected. Empty value is saying that. “null” could be misleading because “null” could actually be a selected text.
> Also what about renaming 'selected' with 'selectedText' .
> 
> 
It’s a local var, renaming would not change any semantic or behavior or would not make code more or less easier to understood.

Shura

**Comment by akolarkunnu** [comment]
ok, fine

**Pull request merged**
